### ISSUE TITLE
Leapwork does not report test status to TeamCity in version 2020.1.673

### ISSUE THREAD

**Issue by twoday-jongislason** [Customatics/Leaptest-Integration#3]
After upgrading to Leapwork 2020.1.673, it seems that Leapwork no longer tells TeamCity the status of the tests that have run. In the screenshot, I run a Leapwork flow that fails, but it reports 0 passed, 0 failed and 0 error test cases. If I run a test that passes, we get the same results.

![image](https://user-images.githubusercontent.com/17744314/79716808-1ed45480-82d8-11ea-8f98-13bbaa8d03f6.png)

**Comment by twoday-jongislason** [comment]
@Divaite @romanchetto @RuralQuagga

**Comment by romanchetto** [comment]
Hello @visma-jonhygomgislason . This is known issue, and it was already fixed. Please update LEAPWORK up to latest release version 2020.1.709. Please reply here, if this helps you or not. Thank you

**Comment by twoday-jongislason** [comment]
Hi @romanchetto, I guess you mean that it has been fixed in the latest version of Leapwork? 

Are you planning on updating this plugin to support the new V4 endpoints? 

I did some digging in your code to see if I could fix the issue, and it seems that the endpoints you use for the STOP_RUN_URI and GET_RUN_STATUS_URI are different from what is described in the documentation here https://www.leapwork.com/product/documentation/rest-api/stop-schedule-by-run-id and here https://www.leapwork.com/product/documentation/rest-api/get-run-status-by-run-id , are you perhaps using deprecated or older versions of the endpoints?

**Comment by romanchetto** [comment]
Hello, @visma-jonhygomgislason.
1) Yes exactly, In LEAPWORK 2020.1.709 it was fixed.
2) Unfortunately, I cannot tell anything about future plugin development and support now.
3) These enpoints still exist  in API v3 now
![image](https://user-images.githubusercontent.com/22563434/80365955-17d9b300-8891-11ea-9603-a14c113856cd.png)
![image](https://user-images.githubusercontent.com/22563434/80366006-2de77380-8891-11ea-8c07-ba9e9f3edc14.png)

**Comment by twoday-jongislason** [comment]
Perfect, thank you. I will attempt an update tomorrow.
